### PR TITLE
Migration from VSTS

### PR DESCRIPTION
**Pull request by athaynes**
This PR updates the repo to use DscResource.Tests and AppVeyor as part of the migration from the private VSTS. Several tests were consolidated to properly use the DscResource.Tests repo. The source code for the resource has only been updated with the required copyright header. All other updates were made to align with the rest of the DSC community resources and guidelines.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2)

### CODE REVIEW

**Comment by regedit32** [comment]
Reviewed 2 of 66 files at r1.
Review status: 2 of 66 files reviewed, 2 unresolved discussions (waiting on @athaynes)

---

*[Tests/Unit/Browser.tests.ps1, line 14 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFXJT4jEypfiwrEoD_a:-LFXJT4jEypfiwrEoD_b:b-2rrspo) ([raw file](https://github.com/microsoft/powerstigdsc/blob/34e935f4d0ff09802df737aee3a54095f812f6b3/Tests/Unit/Browser.tests.ps1#L14)):*
> ```
> {
>     & git @('-C',(Join-Path -Path $moduleRoot -ChildPath '\DSCResource.Tests\'),'pull')
> ```
Do we need this else condition?  Looks like it came from an old template.  it's not consistent with the other tests.

---

*[Tests/Unit/Browser.tests.ps1, line 19 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFXOLYo34qASZ1gFhbo:-LFXOLYpBLPwT6HIrFBh:b-um59o) ([raw file](https://github.com/microsoft/powerstigdsc/blob/34e935f4d0ff09802df737aee3a54095f812f6b3/Tests/Unit/Browser.tests.ps1#L19)):*
> ```PowerShell
> Import-Module (Join-Path -Path $moduleRoot -ChildPath 'Tests\helper.psm1') -Force
> Import-Module (Join-Path -Path $moduleRoot -ChildPath 'DSCResource.Tests\TestHelper.psm1') -Force
> # $TestEnvironment = Initialize-TestEnvironment `
> ```

I noticed you had these commented out.  Was it not working as expected for composites?  If so, we should probably remove the dead code.

---


*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2)*

**Comment by athaynes** [comment]
Review status: 2 of 66 files reviewed, 2 unresolved discussions (waiting on @athaynes and @regedit32)

---

*[Tests/Unit/Browser.tests.ps1, line 14 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFXJT4jEypfiwrEoD_a:-LFvasaOD16ZphOTTfv-:b-6fyiaw) ([raw file](https://github.com/microsoft/powerstigdsc/blob/34e935f4d0ff09802df737aee3a54095f812f6b3/Tests/Unit/Browser.tests.ps1#L14)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

> ```
> {
>     & git @('-C',(Join-Path -Path $moduleRoot -ChildPath '\DSCResource.Tests\'),'pull')
> ```
Do we need this else condition?  Looks like it came from an old template.  it's not consistent with the other tests.
</blockquote></details>

Good catch. That has been updated in all unit tests.

---

*[Tests/Unit/Browser.tests.ps1, line 19 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFXOLYo34qASZ1gFhbo:-LFvblQS-gDTdzsVJdIS:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/34e935f4d0ff09802df737aee3a54095f812f6b3/Tests/Unit/Browser.tests.ps1#L19)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

I noticed you had these commented out.  Was it not working as expected for composites?  If so, we should probably remove the dead code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2)*

**Comment by athaynes** [comment]
Review status: 2 of 66 files reviewed, 2 unresolved discussions (waiting on @regedit32)

---

*[Tests/Unit/Browser.tests.ps1, line 14 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFXJT4jEypfiwrEoD_a:-LFvdKEf-keUO3qSXM1Q:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/34e935f4d0ff09802df737aee3a54095f812f6b3/Tests/Unit/Browser.tests.ps1#L14)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

Good catch. That has been updated in all unit tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2)*

**Comment by jcwalker** [comment]
*[DSCResources/helper.psm1, line 14 at r2](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFw_JM38axRCmMrKXZ5:-LFw_JM38axRCmMrKXZ6:blju6qc) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4358a3f778407e7e1c44c15ee481346070be6c58/DSCResources/helper.psm1#L14)):*
> ```PowerShell
> 
>     .PARAMETER Rule
>         The Stig rule that is being created.
> ```

Best practices and style guidelines says to have the cmdletBinding attribute and outputType on all the functions

---


*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2)*

**Comment by jcwalker** [comment]
*[DSCResources/common/windows.AccountPolicy.ps1, line 18 at r2](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFwbgofABZc6BWbkyiU:-LFwbgofABZc6BWbkyiV:bgmqw9q) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4358a3f778407e7e1c44c15ee481346070be6c58/DSCResources/common/windows.AccountPolicy.ps1#L18)):*
> ```PowerShell
>     )
> 
>     & $sb
> ```

Just a suggestion here to make the code easier to read. The scriptblock class has an Invoke() method.  I think it looks better the call operator.  #JustASuggestion

---


*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2)*

**Comment by jcwalker** [comment]
*[Tests/Integration/Browser.config.ps1, line 9 at r2](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFwf39TEBbxP1F-7Axv:-LFwf39TEBbxP1F-7Axw:beabq4h) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4358a3f778407e7e1c44c15ee481346070be6c58/Tests/Integration/Browser.config.ps1#L9)):*
> ```PowerShell
>         $BrowserVersion,
> 
>         [Parameter(Mandatory = $false)]
> ```

Shouldn't this be Mandatory = $true.  If not style guidelines says the 'Mandatory' key word isn't required.

---


*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2)*

**Comment by jcwalker** [comment]
*[Tests/Integration/WindowsServer.config.ps1, line 25 at r2](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFwgE5CEF2XS3YafpsZ:-LFwgE5CEF2XS3Yafps_:bly9wfp) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4358a3f778407e7e1c44c15ee481346070be6c58/Tests/Integration/WindowsServer.config.ps1#L25)):*
> ```PowerShell
>         $DomainName,
> 
>         [Parameter(Mandatory = $false)]
> ```

Unnecessary Mandatory decoration 
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block

---


*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2)*

**Comment by jcwalker** [comment]
Reviewed 61 of 66 files at r1, 5 of 5 files at r2.
Review status: all files reviewed, 7 unresolved discussions (waiting on @regedit32 and @athaynes)

---

*[Tests/Unit/helper.tests.ps1, line 3 at r2](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFwh9Z44aMLVc1akja9:-LFwh9Z44aMLVc1akjaA:bgjwuhw) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4358a3f778407e7e1c44c15ee481346070be6c58/Tests/Unit/helper.tests.ps1#L3)):*
> ```PowerShell
> [String] $script:moduleRoot = Split-Path -Parent ( Split-Path -Parent $PSScriptRoot )
> 
> Import-Module -Name (Join-Path -Path $moduleRoot -ChildPath 'DscResources\helper.psm1')
> ```

Super nit picky here....you do not have spaces on both sides of the parentheses but you do on the line above it.  It doesn't really matter but would be nice if it were consistent.  

---


*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2)*

**Comment by athaynes** [comment]
Review status: 59 of 66 files reviewed, 7 unresolved discussions (waiting on @jcwalker and @regedit32)

---

*[DSCResources/helper.psm1, line 14 at r2](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFw_JM38axRCmMrKXZ5:-LFx9k0Z-qQj0o8QNeID:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4358a3f778407e7e1c44c15ee481346070be6c58/DSCResources/helper.psm1#L14)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Best practices and style guidelines says to have the cmdletBinding attribute and outputType on all the functions
</blockquote></details>

Done.

---

*[DSCResources/common/windows.AccountPolicy.ps1, line 18 at r2](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFwbgofABZc6BWbkyiU:-LFx9iDpDL-CxKjLdPIi:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4358a3f778407e7e1c44c15ee481346070be6c58/DSCResources/common/windows.AccountPolicy.ps1#L18)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Just a suggestion here to make the code easier to read. The scriptblock class has an Invoke() method.  I think it looks better the call operator.  #JustASuggestion
</blockquote></details>

Done.

---

*[Tests/Integration/Browser.config.ps1, line 9 at r2](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFwf39TEBbxP1F-7Axv:-LFx9eaq8eEU7X_QKty6:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4358a3f778407e7e1c44c15ee481346070be6c58/Tests/Integration/Browser.config.ps1#L9)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Shouldn't this be Mandatory = $true.  If not style guidelines says the 'Mandatory' key word isn't required.
</blockquote></details>

Done.

---

*[Tests/Integration/WindowsServer.config.ps1, line 25 at r2](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFwgE5CEF2XS3YafpsZ:-LFx9d0FD0-5L_senGFL:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4358a3f778407e7e1c44c15ee481346070be6c58/Tests/Integration/WindowsServer.config.ps1#L25)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Unnecessary Mandatory decoration 
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block

</blockquote></details>

Done.

---

*[Tests/Unit/helper.tests.ps1, line 3 at r2](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-LFwh9Z44aMLVc1akja9:-LFx9YLqCMOIrfBQWI6M:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4358a3f778407e7e1c44c15ee481346070be6c58/Tests/Unit/helper.tests.ps1#L3)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Super nit picky here....you do not have spaces on both sides of the parentheses but you do on the line above it.  It doesn't really matter but would be nice if it were consistent.  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2)*

**Comment by jcwalker** [comment]
:lgtm:

---

Review status: 59 of 66 files reviewed, 7 unresolved discussions (waiting on @jcwalker and @regedit32)

---



*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-:-LFxHtMN9wgH93Ea2s26:bnfp4nl)*

**Comment by regedit32** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed, 5 unresolved discussions (waiting on @jcwalker)

---



*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2#-:-LFxb-86233oPLD3U7BS:bnfp4nl)*

**Comment by jcwalker** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed, 5 unresolved discussions (waiting on @jcwalker)

---



*Comments from [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/2)*

**Review by jcwalker — APPROVED** [review]

**Review by regedit32 — APPROVED** [review]

**Pull request merged**
