### PR TITLE
DotNetFramework: Added DotNetFramework STIG Compsite for .NET 4.0

### PR DESCRIPTION
**Pull request by ldillonel**
**Pull Request (PR) description:**

**This Pull Request (PR) fixes the following issues:**

**Task list:**

- [x] Change details added to Unreleased section of README.md (Not required for Convert modules)?
- [x] Added/updated documentation, comment-based help and descriptions where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/17)

### CODE REVIEW

**Review by jcwalker — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/17)* status: all files reviewed, 3 unresolved discussions (waiting on @ldillonel)

___
*[DSCResources/DotNetFramework/DotNetFramework.psd1, line 54 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIrH3YU9sm0e1MMXi_k:-LIrH3YU9sm0e1MMXi_l:bxbb8cd) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/DSCResources/DotNetFramework/DotNetFramework.psd1#L54)):*
> ```PowerShell
> 
> # Modules that must be imported into the global environment prior to importing this module
> # RequiredModules = @()
> ```

Let remove all the unused properties
___
*[DSCResources/DotNetFramework/DotNetFramework.schema.psm1, line 11 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIrHJe0-y-7-d2wWHqL:-LIrHJe0-y-7-d2wWHqM:b-2femtj) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/DSCResources/DotNetFramework/DotNetFramework.schema.psm1#L11)):*
> ```PowerShell
> 
>     .PARAMETER FrameworkVersion
>         The version of the DotNet STIG to apply and monitor
> ```

"The version of .NET the STIG applies to."
___
*[Tests/Integration/DotNetFramework.integration.tests.ps1, line 33 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIrKiXgDQQai5rEyAxn:-LIrKiXgDQQai5rEyAxo:bktldk9) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/Tests/Integration/DotNetFramework.integration.tests.ps1#L33)):*
> ```PowerShell
>     Foreach ($stig in $stigList)
>     {
> ```

Extra line

**Review by chasewilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/17)* status: all files reviewed, 7 unresolved discussions (waiting on @ldillonel)

___
*[DSCResources/DotNetFramework/DotNetFramework.schema.psm1, line 124 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIsZlCl5y41WD6th5G-:-LIsZlCm1oqF9nFywQHe:bktat8t) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/DSCResources/DotNetFramework/DotNetFramework.schema.psm1#L124)):*
> ```PowerShell
>     if ((New-Object Technology).GetType().BaseType.Name -eq 'Enum')
>     {
>         # BEGIN: leave this after the temp fix is removed
> ```

Verify if this uses the Enum but I believe that we should be able to remove the temp fix
___
*[Examples/Sample_DotNetFramework.ps1, line 2 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIs_gA24fD7w-Bgtv0b:-LIs_gA24fD7w-Bgtv0c:b-wh4m09) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/Examples/Sample_DotNetFramework.ps1#L2)):*
> ```PowerShell
> <#
>     In this example, the DotNetFramework 4.0 STIG is processed by the composite resource.
> ```

Should have examples for Exception, SkipRule, SkipRuleType 
___
*[Tests/Integration/DotNetFramework.integration.tests.ps1, line 41 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIsb0nO-gvIw95AipSN:-LIsawgZ-z9OZbZJKxSE:bo9htxl) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/Tests/Integration/DotNetFramework.integration.tests.ps1#L41)):*
> ```
> onfig" `
> ```
Should be aligned with the other lines in the command
___
*[Tests/Integration/DotNetFramework.integration.tests.ps1, line 77 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIsbc0pCM3_0507NAzz:-LIsbc0pCM3_0507NB--:b-31u5x8) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/Tests/Integration/DotNetFramework.integration.tests.ps1#L77)):*
> ```
> #region FOOTER
> Restore-TestEnvironment -TestEnvironment $TestEnvironment
> #endregion
> ```
Should be tabbed over

**Review by ldillonel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/17)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @jcwalker, @chasewilson, and @ldillonel)

___
*[DSCResources/DotNetFramework/DotNetFramework.psd1, line 54 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIrH3YU9sm0e1MMXi_k:-LIv7bS_7YLUW2nmDPh5:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/DSCResources/DotNetFramework/DotNetFramework.psd1#L54)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Let remove all the unused properties
</blockquote></details>

Done.
___
*[DSCResources/DotNetFramework/DotNetFramework.schema.psm1, line 11 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIrHJe0-y-7-d2wWHqL:-LIv7ecB1RifBdfQ3MSu:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/DSCResources/DotNetFramework/DotNetFramework.schema.psm1#L11)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

"The version of .NET the STIG applies to."
</blockquote></details>

Done.
___
*[DSCResources/DotNetFramework/DotNetFramework.schema.psm1, line 124 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIsZlCl5y41WD6th5G-:-LIvpF6v43ZX_bmxDvQ2:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/DSCResources/DotNetFramework/DotNetFramework.schema.psm1#L124)):*
<details><summary><i>Previously, chasewilson (Chase Wilson) wrote…</i></summary><blockquote>

Verify if this uses the Enum but I believe that we should be able to remove the temp fix
</blockquote></details>

Done.
___
*[Examples/Sample_DotNetFramework.ps1, line 2 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIs_gA24fD7w-Bgtv0b:-LIvpnJy6fjloPtYMDQF:b2nx9qs) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/Examples/Sample_DotNetFramework.ps1#L2)):*
<details><summary><i>Previously, chasewilson (Chase Wilson) wrote…</i></summary><blockquote>

Should have examples for Exception, SkipRule, SkipRuleType 
</blockquote></details>

This STIG contains a single registry rule.  The example for Exception, SkipRule, & SkipRulyType are not applicable for this STIG and examples are present for other STIGs.
___
*[Tests/Integration/DotNetFramework.integration.tests.ps1, line 33 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIrKiXgDQQai5rEyAxn:-LIv7mSO1kaetqB797Li:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/Tests/Integration/DotNetFramework.integration.tests.ps1#L33)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Extra line
</blockquote></details>

Done.
___
*[Tests/Integration/DotNetFramework.integration.tests.ps1, line 41 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIsb0nO-gvIw95AipSN:-LIvEwkv6YZz9PPxJKKY:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/Tests/Integration/DotNetFramework.integration.tests.ps1#L41)):*
<details><summary><i>Previously, chasewilson (Chase Wilson) wrote…</i></summary><blockquote>

> ```
> onfig" `
> ```
Should be aligned with the other lines in the command
</blockquote></details>

Done.
___
*[Tests/Integration/DotNetFramework.integration.tests.ps1, line 77 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIsbc0pCM3_0507NAzz:-LIvF6iH4eg-6j7LZQ2s:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/Tests/Integration/DotNetFramework.integration.tests.ps1#L77)):*
<details><summary><i>Previously, chasewilson (Chase Wilson) wrote…</i></summary><blockquote>

> ```
> #region FOOTER
> Restore-TestEnvironment -TestEnvironment $TestEnvironment
> #endregion
> ```
Should be tabbed over
</blockquote></details>

Done.

**Review by ldillonel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/17)* status: 4 of 10 files reviewed, 7 unresolved discussions (waiting on @jcwalker and @chasewilson)

___
*[Examples/Sample_DotNetFramework.ps1, line 2 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-LIs_gA24fD7w-Bgtv0b:-LJP6x3S6QntkNlc2Tlb:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/49a471fb7ce7b1787baa6b0d48e05502a45232bd/Examples/Sample_DotNetFramework.ps1#L2)):*
<details><summary><i>Previously, ldillonel wrote…</i></summary><blockquote>

This STIG contains a single registry rule.  The example for Exception, SkipRule, & SkipRulyType are not applicable for this STIG and examples are present for other STIGs.
</blockquote></details>

Done.

**Review by jcwalker — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-:-LJPGU6Y8A3xmRR1Qjeq:bnfp4nl)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @jcwalker and @chasewilson)

**Review by chasewilson — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/17)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by chasewilson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/17#-:-LJQ6Zew7UXKUm2zYk8r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
