### PR TITLE
Add module version to Import-DscResource cmdlets

### PR DESCRIPTION
**Pull request by camusicjunkie**
If multiple versions are installed of a particular module the composite resource will not load.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/3)

### CODE REVIEW

**Comment by athaynes** [comment]
Can you consolidate PR 3,4,5,6 into a single PR and update the unreleased section of the readme?

**Comment by camusicjunkie** [comment]
I've consolidated all the PRs and updated the readme.md. This was my first set of pull requests ever so I hope you don't mind my ignorance on this 😄 .

**Comment by athaynes** [comment]
NP at all. We're all here to learn. Thanks for jumping into the project. I am not sure why the parsing test is failing in AppVeyor for the xDnsServer though. It works fine on my local machine. @jcwalker @regedit32  do you have any ideas?

**Comment by regedit32** [comment]
Now that we're specifying module versions in the composites, we need to make sure the same versions on installed on the build agent.  This line in the Appveryor.yml needs to be updated to specify `-RequiredVersion` instead of `-MinimumVersion`.

```
- ps: (Import-PowerShellDataFile "$env:APPVEYOR_BUILD_FOLDER\PowerStigDsc.psd1").RequiredModules |
            ForEach-Object { Install-Module $PSItem.moduleName -MinimumVersion $PSItem.ModuleVersion -Repository PSGallery -Scope CurrentUser -Force }
```

**Comment by athaynes** [comment]
@camusicjunkie did you push the changes that @regedit32 outlined to see if that resolves the build failure so we can get this merged in?

**Comment by camusicjunkie** [comment]
I've updated my PR with those changes and the build now passes.

**Review by athaynes — APPROVED** [review]
lgtm

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/3#-:-LH8ojBaD9kUKDHzbm_w:bb7k0qh)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @camusicjunkie)

___
*[appveyor.yml, line 9 at r4](https://reviewable.io/reviews/microsoft/powerstigdsc/3#-LH8nhPM7iafVPcrV3h7:-LH8nhPM7iafVPcrV3h8:bb7k0qh) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4a44c8cf4f535a3e81ba6eb78bf6012ce2be0b01/appveyor.yml#L9)):*
> ```YAML
>     - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
>     - ps: (Import-PowerShellDataFile "$env:APPVEYOR_BUILD_FOLDER\PowerStigDsc.psd1").RequiredModules |
>             ForEach-Object { Install-Module $PSItem.moduleName -MinimumVersion $PSItem.ModuleVersion -Repository PSGallery -Scope CurrentUser -Force }
> ```

lgtm
___
*[PowerStigDsc.psd1, line 35 at r4](https://reviewable.io/reviews/microsoft/powerstigdsc/3#-LH8nlqb5Rcel04DsFuc:-LH8nlqb5Rcel04DsFud:bb7k0qh) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4a44c8cf4f535a3e81ba6eb78bf6012ce2be0b01/PowerStigDsc.psd1#L35)):*
> ```PowerShell
>     @{ModuleName = 'xPSDesiredStateConfiguration'; ModuleVersion = '8.0.0.0'},
>     @{ModuleName = 'xWinEventLog'; ModuleVersion = '1.1.0.0'}
>     )
> ```

lgtm
___
*[README.md, line 149 at r4](https://reviewable.io/reviews/microsoft/powerstigdsc/3#-LH8nsGS0eYkoeeXTaiG:-LH8nsGS0eYkoeeXTaiH:bb7k0qh) ([raw file](https://github.com/microsoft/powerstigdsc/blob/8393b04b2ae1a0ba69571f0869ae7fab6d69f2d5/README.md#L149)):*
> ```Markdown
> 
> * Added ModuleVersion parameter to each Import-DscResource for all composite resources
> ```

lgtm
___
*[DSCResources/Browser/Browser.schema.psm1, line 118 at r4](https://reviewable.io/reviews/microsoft/powerstigdsc/3#-LH8o08X3H6frhUB2asp:-LH8o08X3H6frhUB2asq:bb7k0qh) ([raw file](https://github.com/microsoft/powerstigdsc/blob/8393b04b2ae1a0ba69571f0869ae7fab6d69f2d5/DSCResources/Browser/Browser.schema.psm1#L118)):*
> ```PowerShell
> 
>     Import-DscResource -ModuleName PSDesiredStateConfiguration -ModuleVersion 1.1
>     . "$resourcePath\windows.Registry.ps1"
> ```

lgtm

**Review by athaynes — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 4 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/3)* status: all files reviewed, 4 unresolved discussions (waiting on @camusicjunkie)

**Review by athaynes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/3#-:-LH8p_i599cznakWo_mq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by athaynes — APPROVED** [review]

**Comment by athaynes** [comment]
@jcwalker @regedit32 Can you give this a quick review approve.

**Review by jcwalker — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/3#-:-LH9cp0bCvw4BEsscCgq:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
