### PR TITLE
Updates to ReadMe and examples for SqlServer STIGS #15

### PR DESCRIPTION
**Pull request by chasewilson**
This removes the SqlServer README and updates the project readme with the SqlServer Material. 
Adds SqlServer Resource examples to examples folder.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/16)

### CODE REVIEW

**Review by athaynes — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/16)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @chasewilson, @jcwalker, and @athaynes)

___
*[Examples/Sample_SqlServer_Exception.ps1, line 29 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/16#-LIqggrw4fEyWF9w-5UY:-LIqggrx9S3p9Mg2i3Gw:b-pd5d99) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4c8da222dcf33cfd454280a035dba4a59a4a0855/Examples/Sample_SqlServer_Exception.ps1#L29)):*
> ```PowerShell
>             StigVersion    = '1.17'
>             ServerInstance = 'ServerX\TestInstance'
>             Exception      = @{'V-1000'= @{'ValueData'='1'} }
> ```

This should be a real stig rule, so that the example can be run as is.
___
*[Examples/Sample_SqlServer_SkipRule.ps1, line 28 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/16#-LIqgSSgCTWAFmekzh63:-LIqgSSgCTWAFmekzh64:b-pd5d99) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4c8da222dcf33cfd454280a035dba4a59a4a0855/Examples/Sample_SqlServer_SkipRule.ps1#L28)):*
> ```PowerShell
>             StigVersion    = '1.17'
>             ServerInstance = 'ServerX\TestInstance'
>             SkipRule       = 'V-1000'
> ```

This should be a real stig rule, so that the example can be run as is.

**Review by athaynes — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/16)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @chasewilson, @jcwalker, and @athaynes)

**Review by athaynes — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/16#-:-LIr3D7h3PCCvhss9gs_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @chasewilson and @jcwalker)

___
*[Examples/Sample_SqlServer_Exception.ps1, line 29 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/16#-LIqggrw4fEyWF9w-5UY:-LIr3EMi1FGjifzpCxzC:bnfp4nl) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4c8da222dcf33cfd454280a035dba4a59a4a0855/Examples/Sample_SqlServer_Exception.ps1#L29)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

This should be a real stig rule, so that the example can be run as is.
</blockquote></details>

:lgtm:
___
*[Examples/Sample_SqlServer_SkipRule.ps1, line 28 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/16#-LIqgSSgCTWAFmekzh63:-LIr3IDKB0DA7NOjEsHd:bg7igkv) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4c8da222dcf33cfd454280a035dba4a59a4a0855/Examples/Sample_SqlServer_SkipRule.ps1#L28)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

This should be a real stig rule, so that the example can be run as is.
</blockquote></details>

:lgtm:

**Review by chasewilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/16)* status: all files reviewed, 2 unresolved discussions (waiting on @athaynes and @jcwalker)

___
*[Examples/Sample_SqlServer_Exception.ps1, line 29 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/16#-LIqggrw4fEyWF9w-5UY:-LIr3oFT1Pmhtaopdm8e:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4c8da222dcf33cfd454280a035dba4a59a4a0855/Examples/Sample_SqlServer_Exception.ps1#L29)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

:lgtm:
</blockquote></details>

Done.
___
*[Examples/Sample_SqlServer_SkipRule.ps1, line 28 at r1](https://reviewable.io/reviews/microsoft/powerstigdsc/16#-LIqgSSgCTWAFmekzh63:-LIr3oduDR00WlkoCTHt:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/4c8da222dcf33cfd454280a035dba4a59a4a0855/Examples/Sample_SqlServer_SkipRule.ps1#L28)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

Done.

**Review by athaynes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcwalker)

**Pull request merged**
