### PR TITLE
Change using to Import-Module

### PR DESCRIPTION
**Pull request by camusicjunkie**
There are unnecessary errors with using as it can't find the module. Use Import-Module to alleviate that error.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/8)

### CODE REVIEW

**Comment by athaynes** [comment]
What error message are you getting? @jcwalker @regedit32 Have you guys run into an issue with the using statement?

**Comment by regedit32** [comment]
@athaynes I haven't run into any issues with it, but this would be good for discussion in an open issue.
@camusicjunkie per the [Contribution Guidelines](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md), can you open an Issue with info on what you're seeing?  That would be the best place for everyone to discuss.  Thanks!

**Comment by jcwalker** [comment]
@camusicjunkie what version of PowerShell are you using?  I ran into a problems when using PowerShell 5.0 where the technology class could not be found. The fix was to upgrade to 5.1.

**Comment by athaynes** [comment]
@camusicjunkie can you close this PR? This 'using module' statement needs to be there to import the PowerShell classes from PoweStig.

**Pull request closed without merging**
