### PR TITLE
Issue #12

### PR DESCRIPTION
**Pull request by chasewilson**
This adds the composite for Sql Server including tests. 

There is an update to adjust the path in the test helper. There was an issue with the tests running against xxdf's in the archives as well as the converted STIGS.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/13)

### CODE REVIEW

**Review by jcwalker — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/13)* status: all files reviewed, 10 unresolved discussions (waiting on @chasewilson)

___
*[DSCResources/common/windows.SqlScriptQuery.ps1, line 11 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfugyy69uyMhLdZGtG:-LIfugyz0lfFtm2pgi-I:b-bwsgtl) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/common/windows.SqlScriptQuery.ps1#L11)):*
> ```PowerShell
>         foreach ($db in $Database)
>         {
>             Foreach ( $rule in $rules )
> ```

this should be lowercase to be consistent with the other code in this file.
___
*[DSCResources/SqlServer/readme.md, line 25 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfvLvr2o_hi_q8LQoe:-LIfvLvr2o_hi_q8LQof:bracpxd) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/readme.md#L25)):*
> ```
> The scope that the STIG will cover that the configuration is applying to.
> ```
This reads weird.  Maybe remove "that the configuration is applying to."

You can probably remove "that the configuration is applying to" on all the descriptions.  It's implied.

Also, since this parameter has validateSet it makes sense to mention the possible values
___
*[DSCResources/SqlServer/readme.md, line 26 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfv4y-BBCl_penURRo:-LIfv4y-BBCl_penURRp:bkamx48) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/readme.md#L26)):*
> ```
> hostiing
> ```
Should be hosting
___
*[DSCResources/SqlServer/SqlServer.psd1, line 24 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfxSXIB3MiIa3lywGN:-LIfxSXIB3MiIa3lywGO:bqf4aat) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/SqlServer.psd1#L24)):*
> ```PowerShell
> 
> # Author of this module
> Author = 'chasewilson'
> ```

Author = 'Microsoft Corporation'
___
*[DSCResources/SqlServer/SqlServer.psd1, line 27 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfxJxQ3L-sSJSlS72c:-LIfxJxQ3L-sSJSlS72d:b-h7g6io) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/SqlServer.psd1#L27)):*
> ```PowerShell
> 
> # Company or vendor of this module
> CompanyName = 'Unknown'
> ```

CompanyName = 'Microsoft Corportation'
___
*[DSCResources/SqlServer/SqlServer.schema.psm1, line 78 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfxsHF1Xxtv0h7RJPv:-LIfxsHF1Xxtv0h7RJPw:b-u24ofk) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/SqlServer.schema.psm1#L78)):*
> ```PowerShell
>         [string]
>         $SqlRole,
>         
> ```

Remove blank spaces
___
*[DSCResources/SqlServer/SqlServer.schema.psm1, line 152 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfy12L91ZWtxe4WUmL:-LIfy-8KDdbAngO5Vpzb:b1957m7) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/SqlServer.schema.psm1#L152)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     # BEGIN: This is a temporary fix until PowerStig has migrated the technolgy class to an enumeration
>     if ((New-Object Technology).GetType().BaseType.Name -eq 'Enum')
>     {
>         # BEGIN: leave this after the temp fix is removed
>         $technology = [Technology]::SqlServer
>         # END: leave this after the temp fix is removed
> ```
</details>

 You can remove this and only use the code the references the Technology Enum now.
___
*[Tests/CompositeResourceFilter.psd1, line 6 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIg-XcS39aQrbeFjjSF:-LIg-XcS39aQrbeFjjSG:b-8v8fu0) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/Tests/CompositeResourceFilter.psd1#L6)):*
> ```PowerShell
> 
>     SqlServer        = @("*Instance*", "*Database*")
>     
> ```

remove blank spaces here and the lines below
___
*[Tests/Integration/SqlServer.config.ps1, line 13 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIg0Aj53m8uNblrwlGX:-LIg0Aj53m8uNblrwlGY:begunvh) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/Tests/Integration/SqlServer.config.ps1#L13)):*
> ```PowerShell
>         $SqlRole,
> 
>         [Parameter(Mandatory = $false)]
> ```

Should be [Parameter()]

per the style guidelines
___
*[Tests/Integration/SqlServer.config.ps1, line 44 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIg0SDZBH_bB1QLYqcv:-LIg0SDZBH_bB1QLYqcw:b4whyrt) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/Tests/Integration/SqlServer.config.ps1#L44)):*
> ```PowerShell
>         $SqlRole,
> 
>         [Parameter(Mandatory = $false)]
> ```

[Parameter()]

**Review by chasewilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/13)* status: all files reviewed, 10 unresolved discussions (waiting on @jcwalker)

___
*[DSCResources/common/windows.SqlScriptQuery.ps1, line 11 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfugyy69uyMhLdZGtG:-LIg2sBSAIQW9tzAKDDO:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/common/windows.SqlScriptQuery.ps1#L11)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

this should be lowercase to be consistent with the other code in this file.
</blockquote></details>

Done.
___
*[DSCResources/SqlServer/readme.md, line 25 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfvLvr2o_hi_q8LQoe:-LIg2spf0NM-J2xR5ool:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/readme.md#L25)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

> ```
> The scope that the STIG will cover that the configuration is applying to.
> ```
This reads weird.  Maybe remove "that the configuration is applying to."

You can probably remove "that the configuration is applying to" on all the descriptions.  It's implied.

Also, since this parameter has validateSet it makes sense to mention the possible values
</blockquote></details>

Done.
___
*[DSCResources/SqlServer/readme.md, line 26 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfv4y-BBCl_penURRo:-LIg31DIArImVilsg9Sy:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/readme.md#L26)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

> ```
> hostiing
> ```
Should be hosting
</blockquote></details>

Done.
___
*[DSCResources/SqlServer/SqlServer.psd1, line 24 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfxSXIB3MiIa3lywGN:-LIg38KP-ifvTa4Ca3iC:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/SqlServer.psd1#L24)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Author = 'Microsoft Corporation'
</blockquote></details>

Done.
___
*[DSCResources/SqlServer/SqlServer.psd1, line 27 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfxJxQ3L-sSJSlS72c:-LIg3Go27cMQwvYhAXba:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/SqlServer.psd1#L27)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

CompanyName = 'Microsoft Corportation'
</blockquote></details>

Done.
___
*[DSCResources/SqlServer/SqlServer.schema.psm1, line 78 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfxsHF1Xxtv0h7RJPv:-LIg3cPPCobTET8paVx9:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/SqlServer.schema.psm1#L78)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Remove blank spaces
</blockquote></details>

Done.
___
*[DSCResources/SqlServer/SqlServer.schema.psm1, line 152 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIfy12L91ZWtxe4WUmL:-LIg3vyz4UTzI8CYGIj7:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/DSCResources/SqlServer/SqlServer.schema.psm1#L152)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

> ```
>     # BEGIN: This is a temporary fix until PowerStig has migrated the technolgy class to an enumeration
>     if ((New-Object Technology).GetType().BaseType.Name -eq 'Enum')
>     {
>         # BEGIN: leave this after the temp fix is removed
>         $technology = [Technology]::SqlServer
>         # END: leave this after the temp fix is removed
> ```
 You can remove this and only use the code the references the Technology Enum now.
</blockquote></details>

Done.
___
*[Tests/CompositeResourceFilter.psd1, line 6 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIg-XcS39aQrbeFjjSF:-LIg45y8EC8MX__DxgqI:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/Tests/CompositeResourceFilter.psd1#L6)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

remove blank spaces here and the lines below
</blockquote></details>

Done.
___
*[Tests/Integration/SqlServer.config.ps1, line 13 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIg0Aj53m8uNblrwlGX:-LIg4DGT3MJZZULrvZ7I:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/Tests/Integration/SqlServer.config.ps1#L13)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

Should be [Parameter()]

per the style guidelines
</blockquote></details>

Done.
___
*[Tests/Integration/SqlServer.config.ps1, line 44 at r3](https://reviewable.io/reviews/microsoft/powerstigdsc/13#-LIg0SDZBH_bB1QLYqcv:-LIg4HBN1V_IIURvHvRN:b-896fix) ([raw file](https://github.com/microsoft/powerstigdsc/blob/7f3cba35ad8d5c496b5427177b485d14a2ccf53a/Tests/Integration/SqlServer.config.ps1#L44)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

[Parameter()]
</blockquote></details>

Done.

**Review by ldillonel — APPROVED** [review]
> Reviewed 3 of 10 files at r1, 1 of 1 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/13)* status: all files reviewed, 10 unresolved discussions (waiting on @jcwalker)

**Review by jcwalker — APPROVED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/microsoft/powerstigdsc/13)* status: all files reviewed, 10 unresolved discussions (waiting on @jcwalker)

**Pull request merged**
